(G-CODE GENERATED BY FLATCAM v2024.4 - www.flatcam.org - Version Date: 2024/04/15)

(Name: latihankicad-PTH.drl_1_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Monday, 03 August 2026 at 02:52)

(This preprocessor is the default preprocessor used by FlatCAM.)
(It is made to work with MACH3 compatible motion controllers.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.7)
(Tool: 2 -> Dia: 0.8)
(Tool: 3 -> Dia: 0.9)
(Tool: 4 -> Dia: 1.1)
(Tool: 5 -> Dia: 1.2)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 300)
(Tool: 2 -> Feedrate: 300)
(Tool: 3 -> Feedrate: 300)
(Tool: 4 -> Feedrate: 300)
(Tool: 5 -> Feedrate: 300)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)
(Tool: 3 -> Feedrate Rapids: 1500)
(Tool: 4 -> Feedrate Rapids: 1500)
(Tool: 5 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.7)
(Tool: 2 -> Z_Cut: -1.7)
(Tool: 3 -> Z_Cut: -1.7)
(Tool: 4 -> Z_Cut: -1.7)
(Tool: 5 -> Z_Cut: -1.7)

(Tools Offset: )
(Tool: 1 -> Offset Z: 0.0)
(Tool: 2 -> Offset Z: 0.0)
(Tool: 3 -> Offset Z: 0.0)
(Tool: 4 -> Offset Z: 0.0)
(Tool: 5 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)
(Tool: 2 -> Z_Move: 2)
(Tool: 3 -> Z_Move: 2)
(Tool: 4 -> Z_Move: 2)
(Tool: 5 -> Z_Move: 2)

(Z Toolchange: 15 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 0.5 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Preprocessor Excellon: default)

(X range:   62.3900 ...  230.5520  mm)
(Y range: -128.4500 ...  -50.2000  mm)

(Spindle Speed: 0 RPM)
G21
G90
G94

G01 F300.00

M5
G00 Z15.0000
T1
G00 X0.0000 Y0.0000                
M6
(MSG, Change to Tool Dia = 0.7000 ||| Total drills for tool T1 = 31)
M0
G00 Z15.0000

G01 F300.00
M03
G00 X119.3800 Y-96.5200
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X207.0100 Y-85.0900
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X207.0100 Y-59.6900
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X186.6900 Y-85.0900
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X186.6900 Y-59.6900
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X91.4400 Y-76.2000
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X91.4400 Y-50.8000
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X230.0020 Y-101.5950
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X230.0020 Y-99.0550
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X230.0020 Y-96.5150
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X230.0020 Y-93.9750
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X208.2800 Y-96.5200
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X208.2800 Y-93.9800
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X186.6220 Y-96.5200
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X186.6220 Y-93.9800
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X165.1000 Y-128.0500
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X165.1000 Y-100.5500
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X147.3200 Y-101.6000
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X147.3200 Y-99.0600
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X147.3200 Y-96.5200
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X147.3200 Y-93.9800
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X139.7000 Y-101.6000
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X139.7000 Y-99.0600
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X139.7000 Y-96.5200
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X139.7000 Y-93.9800
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X91.4400 Y-115.3500
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X91.4400 Y-87.8500
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X62.7900 Y-107.6800
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X62.7900 Y-105.6800
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X121.9200 Y-99.0600
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X121.9200 Y-93.9800
G01 Z-1.7000
G01 Z0
G00 Z2.0000
M05
G00 Z0.50


